### ISSUE TITLE
UI - view person - update UI - using existing view, but more detailed

### ISSUE THREAD

**Issue by lavanyagarg112** [AY2425S1-CS2103T-T13-4/tp#106]

**Comment by Ponharish** [comment]
## Description of the New UI

### Summary:
 *This UI is rendered when the doctor uses Find command. The new UI provides a comprehensive detail about the patient or Caregiver.

### Key Updates:
*New UI
*New stylesheets for adding style to this new display
*New Fxml Files to supporting this new UI

### Notes for Reviewers:
•	Please verify that all the fields are displayed in a valid format and are easy to read.
