### ISSUE TITLE
Issue with link workflow - unknown

### ISSUE THREAD

**Issue by lavanyagarg112** [AY2425S1-CS2103T-T13-4/tp#189]
## The issue:

When there is a circular link, the deletelink command behaves in a very different way. it resulted in removal of person from the list view, and unusual behaviour of linking.

Needs further investigation. It is not sure if it is an error in `deletelink`, `link`, `find`, or `list`? or something else?

## System:

I am using MacOS and the jar file.

## Steps to reproduce the issue:

1. `clear confirm` (if you want to start fresh)
2. `add n/John Doe nric/S8484131E p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/backPain role/patient`
3. `add n/Alex Yeoh nric/S8020163Z p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25  role/caregiver`
4. `link patient/S8484131E caregiver/S8020163Z`
5. `edit S8484131E role/patient role/caregiver`
6. `edit S8020163Z role/patient role/caregiver`
7. `link patient/S8484131E caregiver/S8020163Z` - the link happens again (This is because of another known issue: #190 )
8. `find n/Alex`
9. `deletelink caregiver/S8484131E patient/S8020163Z` - John is not shown in list... (with a message that link is deleted, could be due to #191 )
10. `deletelink patient/S8484131E caregiver/S8020163Z` - link is deleted again?
11. `deletelink patient/S8484131E caregiver/S8020163Z` - now shows that link doesnt exist
12. `find n/Alex`
13. `list` - John is shown now!

**Comment by Ponharish** [comment]
Once the 5th command `edit S8484131E role/patient role/caregiver` is executed, the existing link created by the 4th command is deleted. 
This issue has been highlighted in #180

**Comment by Ponharish** [comment]
> `deletelink caregiver/S8484131E patient/S8020163Z` - John is not shown in list
This is happening due to the fact that the model is not being updated

For example, 
If i execute this command `find n/harish n/alex` 2 people would be listed
Then, if I attempt to execute this command `deletelink caregiver/S8484131E patient/S8020163Z' 
or even a valid command `deletelink patient/S8484131E caregiver/S8020163Z`
The output given is:

<img width="702" alt="Screenshot 2024-11-05 at 11 28 41 AM" src="https://github.com/user-attachments/assets/676ddbe3-be1c-4c90-9fc8-a037387cb4b5">

Summary: The model is not being updated when `deletelink` is executed

**Comment by lavanyagarg112** [comment]
> Once the 5th command `edit S8484131E role/patient role/caregiver` is executed, the existing link created by the 4th command is deleted. This issue has been highlighted in #180

Oh I see, I had missed that issue earlier. I think even when editing something other than the role results in this?

**Comment by lavanyagarg112** [comment]
@AY2425S1-CS2103T-T13-4/developers  Ok I think this should work now, will try again once the rest of the PRs are merged

**Comment by pradyuprasad** [comment]
@lavanyagarg112 can help check now

**Comment by lavanyagarg112** [comment]
Point 7, edit still removes existing links
