### ISSUE TITLE
Add Appointment command error message can be more specific

### ISSUE THREAD

**Issue by suhayl13** [AY2425S1-CS2103T-T13-4/tp#196]
<img width="1068" alt="Screenshot 2024-11-03 at 11 37 47 PM" src="https://github.com/user-attachments/assets/0bba0a16-3c33-41b7-9794-e32b511f5ff2">

The error message can be more specific to remove the unnecessary stuff before the prefixes. My implementation to throw this error is as follows:

```
if (!argMultiMap.getPreamble().equals("")) {
            throw new ParseException("Please do not enter anything before the keywords!\n"
            + "Please remove this from your input: " + keywords.getPreamble());
        }     
```

**Comment by lavanyagarg112** [comment]
@suhayl13 if I am not wrong, the error message here is due to the incorrect date format? otherwise it ignores the 1212. So if I understand correctly, you are suggesting we actually raise an error for that, right?
