### ISSUE TITLE
Link example command does not have valid NRIC 

### ISSUE THREAD

**Issue by pradyuprasad** [AY2425S1-CS2103T-T13-4/tp#214]
A bit of a nitpick but the link command's example NRICs should not fail when I try them

<img width="587" alt="image" src="https://github.com/user-attachments/assets/0d27854e-a4b8-483f-8924-fb743301ebe1">

**Comment by lavanyagarg112** [comment]
Will change, thanks

**Comment by lavanyagarg112** [comment]
@pradyuprasad just to clarify, these are also going to be NRIC of people who may not exist in the system (since that depends on the data), but rather just NRICs which are valid in terms of the NRIC constraints themselves
