### ISSUE TITLE
Self-Linking Error with Dual Roles in Single Entry

### ISSUE THREAD

**Issue by pradyuprasad** [AY2425S1-CS2103T-T13-4/tp#215]
Description: When adding a person with both role/patient and role/caregiver in a single entry, attempting to link the person to themselves using the link command results in the error "This link already exists in CareLink". This issue arises even though no explicit link was created.

1. add n/John Smith nric/S9841776A p/91234567 e/johnsmith@example.com a/123, Bishan Street 12, #05-45 role/patient role/caregiver
2. link patient/S9841776A caregiver/S9841776A

Expected Behavior: The system should allow the link command without error, as no explicit link was previously created. Dual roles in a single entry should not imply an existing link.

Actual Behavior: The system throws an error: "This link already exists in CareLink".

**Comment by lavanyagarg112** [comment]
Oh I think I will just make the error more meaningful to show that the person cannot link with themselves, thanks for pointing it out
