### ISSUE TITLE
Improve Error Message for Linking with Non-Existent NRIC

### ISSUE THREAD

**Issue by pradyuprasad** [AY2425S1-CS2103T-T13-4/tp#216]
Description: When attempting to create a link between a patient and a caregiver, if one of the provided NRICs does not exist in the CareLink system, the error message returned is "Incorrect NRIC. Person not found". This message lacks clarity, as it does not specify which NRIC (patient or caregiver) is not found. This can be confusing for users when troubleshooting linking issues.

Steps to Reproduce:

Ensure that NRIC S9841776A (John Smith) exists in CareLink.
link patient/S9841776A caregiver/S6086277Z
Observe the error message: "Incorrect NRIC. Person not found"
Expected Behavior: The error message should clearly indicate which NRIC is not found. For example:

"Caregiver NRIC S6086277Z not found in CareLink" or
"Patient NRIC S6086277Z not found in CareLink"
Actual Behavior: The system displays a generic error message: "Incorrect NRIC. Person not found", which does not specify whether it’s the patient or caregiver NRIC that is missing from the system.

**Comment by lavanyagarg112** [comment]
Noted, thanks for pointing this out
