### ISSUE TITLE
Allow Cross-Linking for Dual-Role Users in Patient-Caregiver Relationships

### ISSUE THREAD

**Issue by pradyuprasad** [AY2425S1-CS2103T-T13-4/tp#218]
**Description:**  
When two users each have both `PATIENT` and `CAREGIVER` roles, CareLink allows only a one-directional link (e.g., linking John Smith as a patient to Sam Tan as a caregiver). However, attempting to create the reverse link (Sam Tan as a patient and John Smith as a caregiver) results in an error. This restriction prevents mutual caregiving relationships, which are often needed in real-world care settings.

**Steps to Reproduce:**

1. Add two users with both roles:  
   add n/John Smith nric/S9841776A p/91234567 e/johnsmith@example.com a/123 Bishan Street 12 #05-45 role/patient role/caregiver  
   add n/Sam Tan nric/S7382917H p/91029382 e/samtan@example.com a/Blk 123 Bukit Timah Street 32 #12-12 role/patient role/caregiver  

2. Link John Smith to Sam Tan in a patient-caregiver relationship:  
   link patient/S9841776A caregiver/S7382917H  

3. Attempt to create the reverse link (Sam Tan as patient, John Smith as caregiver):  
   link patient/S7382917H caregiver/S9841776A  

**Expected Behavior:**  
The system should allow the reverse link, supporting mutual caregiving relationships between two dual-role users.

**Actual Behavior:**  
CareLink denies the second link attempt with an error, blocking reciprocal patient-caregiver relationships.

**Impact:**  
This restriction limits CareLink’s flexibility in managing real-life scenarios where two individuals may support each other reciprocally in caregiving roles.

**Suggested Solution:**  
Allow dual-role users to be linked in both directions as patient-caregiver and caregiver-patient without restriction.

**Comment by lavanyagarg112** [comment]
This is actually intentional because I believed we could not have the patient and caregiver having dual roles for each other, especially since this is for elderly patients. However, I can still allow this behaviour if we believe it could be possible?
