### ISSUE TITLE
Debugging code can be removed from AddAppointmentParser

### ISSUE THREAD

**Issue by AngPengXuan** [AY2425S1-CS2103T-T13-4/tp#234]
![Screenshot from 2024-11-06 14-52-38](https://github.com/user-attachments/assets/3e58a1be-4e24-4bc8-a24c-3212afd4ea8a)

The print statements are not necessary as they will be caught by the arePrefixesPresent check later.

**Comment by lavanyagarg112** [comment]
I actually removed these while adding check for preamble in #226
