### ISSUE TITLE
[PE-D][Tester A] Duplicate “CareLink UserGuide”header in UserGuide 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-4/tp#249]
There are duplicate titles for CareLink User Guide as well as a User Guide title there. This could have been due to merge conflicts. Optimally have 1 “CareLink User Guide” only to have a neater User Guide.

![image.png](https://raw.githubusercontent.com/ITLimJiaWei/ped/main/files/b56ef76c-696a-406c-a7ef-c610649c026c.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ITLimJiaWei/ped#2

**Comment by Ponharish** [comment]
Same as #247

**Comment by Ponharish** [comment]
Will be fixed in #247
