### ISSUE TITLE
[PE-D][Tester C] Find shows many users and I need to use mouse

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-4/tp#291]
# Find command

When find command shows multiple users after executing `find al`, I will need to scroll and use the mouse. This violates the "Constraint-Typing-Preferred" constraint.
![image.png](https://raw.githubusercontent.com/choonzies/ped/main/files/5eb6dbf5-b128-45ab-90ab-b85b89a9e62f.png)

![image.png](https://raw.githubusercontent.com/choonzies/ped/main/files/08b59a0c-3b6f-454a-9899-90e91176ef6f.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: choonzies/ped#12

**Comment by lavanyagarg112** [comment]
Not a bug, can still do it with a mouse. use a tab key. Putting it in the UG as #299

**Comment by Ponharish** [comment]
use tab key twice, and use arrow. It works perfectly

tab+tab+ arrow keys (up or down)
