### ISSUE TITLE
[PE-D][Tester D] fullscreen help button bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-4/tp#292]
when im on full screen mode of the app and click on the help button, it would bring me to another full screened page that is displayed here, rather than a pop up 

![image.png](https://raw.githubusercontent.com/dominic2412/ped/main/files/6dfd1c9b-6712-4ac4-8429-802437581718.png)

remedy: you might want to juz restrict the resizing of the windows as we had a lot of bugs from here also

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: dominic2412/ped#13

**Comment by lavanyagarg112** [comment]
Behaviour of pop-up is due to macos.

**Comment by lavanyagarg112** [comment]
can put in UG as a known issue as well
