### ISSUE TITLE
[PE-D][Tester E] Error message showing incorrect

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-4/tp#308]
![image.png](https://raw.githubusercontent.com/tckeong/ped/main/files/4d62ffd3-6270-494f-9e8f-9fdffa4c0692.png)

The format of command and time are all correct according to UG, but the error message keep showing invalid time.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tckeong/ped#6

**Comment by lavanyagarg112** [comment]
The format of the command is correct. there is no `end/` prefix
