### ISSUE TITLE
[PE-D][Tester E] Delete appointment error

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-4/tp#309]
![image.png](https://raw.githubusercontent.com/tckeong/ped/main/files/bcd4bedd-ea81-4c75-b857-3fd933f7675a.png)

The appointment actually exists, but it shows the appointment does not exist.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tckeong/ped#7

**Comment by lavanyagarg112** [comment]
the tester put the wrong NRIC, the NRIC must be that of the person with whom the appointment is made, not their caregiver
