### ISSUE TITLE
Test help command in full screen for windows and linux

### ISSUE THREAD

**Issue by suhayl13** [AY2425S1-CS2103T-T13-4/tp#322]
Test out help command in full screen for windows and linux. Refer to #292. 

1. Open the application 
2. Ensure that the application is in **fullscreen**.
3. Type out `help` command.
4. Observe if the help windows opens as a pop up or in a separate full screen window.
5. Repeat 3-4 for a few times in Windows and Linux and check if the app crashes

**Comment by AngPengXuan** [comment]
Ubuntu 22.04 - No issues, able to use help command in full screen

**Comment by AngPengXuan** [comment]
I tested this in both Windows 11 and Ubuntu 22.04 (Linux) and have no issues, behavior is exactly the same with a small pop up showing the help link regardless of whether the application was full screen or not full screen. Repeating a few times shows no change in behavior.
